cmd/compile: make all line numbers x.go:1
And comment out an invariant in dwinl.go that's broken by this.
That will probably break debugging in un-fun ways. :(

Backtraces should still work, with function names,
but all line numbers will display as x.go:1.

This breaks any tests that depend on correct line numbers.
For example, net/http:

--- FAIL: TestWriteHeaderNoCodeCheck_h1hijack (0.00s)
    x.go:1: stderr output = "http: response.WriteHeader on hijacked connection from net/http_test.testWriteHeaderAfterWrite.func1 (x.go:1)"; want "http: response.WriteHeader on hijacked connection from net/http_test.testWriteHeaderAfterWrite.func1 (clientserver_test.go:"
--- FAIL: TestWriteHeaderNoCodeCheck_h1 (0.01s)
    x.go:1: stderr output = "http: superfluous response.WriteHeader call from net/http_test.testWriteHeaderAfterWrite.func1 (x.go:1)"; want "http: superfluous response.WriteHeader call from net/http_test.testWriteHeaderAfterWrite.func1 (clientserver_test.go:"
FAIL
FAIL	net/http	13.940s


This shrinks binaries by about 10%:

file      before    after     Δ         %     
addr2line 4415680   4022464   -393216   -8.905%
api       5256224   4707360   -548864   -10.442%
asm       5098312   4553544   -544768   -10.685%
buildid   2901096   2606184   -294912   -10.166%
cgo       4843608   4360280   -483328   -9.979%
compile   19983664  17583408  -2400256  -12.011%
cover     5292392   4772200   -520192   -9.829%
dist      3718888   3333864   -385024   -10.353%
doc       4071904   3645920   -425984   -10.462%
fix       3422024   3069768   -352256   -10.294%
link      6755112   6062888   -692224   -10.247%
nm        4373520   3980304   -393216   -8.991%
objdump   4763232   4324960   -438272   -9.201%
pack      2364760   2110808   -253952   -10.739%
pprof     14618708  13406292  -1212416  -8.294%
test2json 2889496   2578200   -311296   -10.773%
trace     11783892  10743508  -1040384  -8.829%
vet       7231080   6518376   -712704   -9.856%
total     113783592 102380328 -11403264 -10.022%

Change-Id: I56c7540ea856a3bdccf8d44b5c3dbd4803545015